/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_blockchain_free: (a: number, b: number) => void;
export const blockchain_new: () => number;
export const blockchain_add_message_and_mine: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const blockchain_mine_block_and_get: (a: number) => [number, number];
export const blockchain_add_validator: (a: number, b: number, c: number, d: number) => void;
export const blockchain_add_transaction: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const blockchain_add_message: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const blockchain_deploy_trading_contract: (a: number, b: number, c: number) => number;
export const blockchain_call_contract_buy: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const blockchain_call_contract_sell: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const blockchain_get_contract_order_book: (a: number) => [number, number];
export const blockchain_get_contract_trades: (a: number) => [number, number];
export const blockchain_mine_block: (a: number) => number;
export const blockchain_get_chain_length: (a: number) => number;
export const blockchain_get_pending_count: (a: number) => number;
export const blockchain_get_validator_count: (a: number) => number;
export const blockchain_get_latest_block_json: (a: number) => [number, number];
export const blockchain_get_transactions_json: (a: number) => [number, number];
export const blockchain_get_blockchain_summary: (a: number) => [number, number];
export const blockchain_add_p2p_transaction: (a: number, b: number, c: number) => number;
export const blockchain_add_p2p_block: (a: number, b: number, c: number) => number;
export const blockchain_get_sync_summary: (a: number) => [number, number];
export const blockchain_prepare_enterprise_sync: (a: number) => [number, number];
export const blockchain_set_last_sync_block: (a: number, b: number) => void;
export const __wbg_orderbook_free: (a: number, b: number) => void;
export const orderbook_new: () => number;
export const orderbook_place_buy_order: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const orderbook_place_sell_order: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const orderbook_get_order_book_json: (a: number) => [number, number];
export const orderbook_get_recent_trades_json: (a: number) => [number, number];
export const main: () => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_3: WebAssembly.Table;
export const __wbindgen_start: () => void;
